version: "3"

vars:
  VERSION:
    sh: git describe --tags --exact-match 2>/dev/null || git rev-parse --short HEAD

tasks:
  run:
    cmds:
      - go run ./cmd/p86l

  run:debug:
    cmds:
      - P86L_DEBUG=logs go run ./cmd/p86l

  build:debug:
    cmds:
      - go build -tags release -ldflags "-s -w" -trimpath -o ./bin/ ./cmd/p86l

  build:windows:
    cmds:
      - GOOS=windows GOARCH=amd64 go build -tags 'release' -ldflags "-s -w -X main.version={{.VERSION}} -X=runtime.godebugDefault=asyncpreemptoff=1 -H=windowsgui" -trimpath -o ./bin/Project-86-Launcher-{{.VERSION}}.exe ./cmd/p86l

  build:windows-cjk:
    cmds:
      - GOOS=windows GOARCH=amd64 go build -tags 'release,cjk' -ldflags "-s -w -X main.version={{.VERSION}} -X=runtime.godebugDefault=asyncpreemptoff=1 -H=windowsgui" -trimpath -o ./bin/Project-86-Launcher-cjk-{{.VERSION}}.exe ./cmd/p86l
